version: '3.8'

services:

  primary-db:
    image: postgres:14
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/primary/postgres.conf:/etc/postgresql/postgresql.conf
      - ./data/primary/init:/docker-entrypoint-initdb.d
  secondary-db:
    image: postgres:14
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    restart: always
    depends_on: [primary-db]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./data/secondary/postgres.conf:/etc/postgresql/postgresql.conf
      - ./data/secondary/init:/docker-entrypoint-initdb.d
